# Generated by Django 5.2.4 on 2025-07-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ewaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ewaste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_point', to='accounts.ewaste')),
            ],
        ),
    ]
