# Generated by Django 5.2.4 on 2025-07-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ecopoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='ewaste',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('awaiting_drop', 'Awaiting Drop'), ('received', 'Received'), ('rejected', 'Rejected'), ('rewarded', 'Rewarded')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='ewaste',
            name='drop_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dropcenter'),
        ),
    ]
